server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/card_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: CejzoEx6o+/eipovtB+oQMbcCi0eDAobJ54k7/xN/hY=
  ttl: 10h

crypto:
  aes:
    key: W8kqbtv9Zt+XTeBoiDKqWAY8oVv5zwPyTismIoD5gL8=